server:
  port: 8888
spring:
  application:
    name: foolcat-cloud-gateway-server   #唯一名称
  cloud:
    nacos:
      discovery:
        server-addr: nacos.foolcat.xyz:8848  #Nacos 链接地址
    #        namespace: e23b1149-8fa2-4d6e-aa65-00ce8d78d266 #Nacos 命名空间ID
    #          config:
    #            server-addr: nacos.foolcat.xyz:8848  #Nacos 链接地址
    #            namespace: e23b1149-8fa2-4d6e-aa65-00ce8d78d266 #Nacos 命名空间ID
    #            group: DEFAULT_GROUP  # 默认分组就是DEFAULT_GROUP，如果使用默认分组可以不配置
    #            file-extension: yml   #默认properties
    gateway:
      discovery:
        locator:
          enabled: true    #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务
          lower-case-service-id: true  #是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了
      # 路由数组[路由 就是指定当请求满足什么条件的时候转到哪个微服务]
      routes:
        - id: admin-service-router             # 当前路由的标识, 要求唯一
          uri: lb://admin-service       # lb指的是从 nacos 中按照名称获取微服务,并遵循负载均衡策略
          predicates: # 断言(就是路由转发要满足的条件)
            - Path=/admin/**             # 当请求路径满足Path指定的规则时,才进行路由转发
          filters: # 过滤器,请求在传递过程中可以通过过滤器对其进行一定的修改
            - StripPrefix=1              # 转发之前去掉1层路径
    sentinel:
      transport:
        port: 8719
        dashboard: sentinel.foolcat.xyz:8858
      datasource:
        ds1.nacos:
          serverAddr: nacos.foolcat.xyz:8848
          dataId: gateway-sentinel-gw-flow
          ruleType: gw_flow
        ds2.naos:
          serverAddr: nacos.foolcat.xyz:8848
          dataId: gateway-sentinel-api-group
          ruleType: api_group