server:
  port: 8851
spring:
  application:
    name: authorization-server
  cloud:
    nacos:
      discovery:
        server-addr: nacos.foolcat.xyz:8848
  #        namespace: e23b1149-8fa2-4d6e-aa65-00ce8d78d266
  redis:
    host: redis.foolcat.xyz
    port: 6379